### PR TITLE
Reskin template

### PR DESCRIPTION
**Pull request by gvn**
# WIP – Don't merge

Related to #1

### CODE REVIEW

**Comment by gvn** [comment]
@sabrinang can you give this a design review?

https://mozilla.github.io/web-lit-core/

**Comment by sabrinang** [comment]
@gvn This is coming together and the features in the whitepaper (suggest edits & table of contents) will be really handy!

### Design Feedback
**Grid**
- Make the container/column width match foundation and pulse site (so line length isn't too long and matches other)
image

**Side Bar Navigation**
- Make hover state seen on Overview and Whitepaper from blue to yellow and apply to 1 Overview & 2 More info subsections

**Typography**
- Change body copy & footer copy from Fira Sans to Nunito Sans (matches foundation site)
- Reduce line-height for bulleted and numbered lists by half (~0.7 rem) it is looking a bit spaced apart

**Features**
- Do we have the highlight box feature and highlight lists feature? https://github.com/mozilla/foundation.mozilla.org/issues/986#issuecomment-362734645 (not sure if it is present since the demo doesn’t have it)
- Can the user also make multiple columns? (example: 2 column glossary https://github.com/mozilla/foundation.mozilla.org/issues/986#issuecomment-362666440 )

**Comment by gvn** [comment]
Ok, made those tweaks as much as possible. There isn't really a way to do the highlight box as designed with the header text inside without hacks since the markdown results in such basic HTML and there isn't a previous sibling selector in CSS. Multiple columns aren't really possible either without hacks.

I did do a yellow box style for ordered lists, so there's that now.

Can you take another look @sabrinang ?

**Comment by sabrinang** [comment]
The grid and type is looking great. Having the highlighted yellow box is better than none so we can go with that. 

I got some feedback from crit that the anchored section links feel jumpy and a bit disoriented when they clicked on it. I think there are two things we can help improve this:

- Can we have a scrolling transition when users click to go to a subsection? _(see old template)_
- Can we hide the subsections in the nav until the main page is clicked?
   - This is because when users click directly on it (for example, *2 More Info*) users don't immediately know they are within the White Paper page so we shouldn't see the options until they are in that page. Also, since it has a TOC we may want the navigation to contain the exact same sub sections too for consistency. I would like to hear what you suggest for this @gvn

**Comment by gvn** [comment]
@sabrinang made those tweaks. The TOC that shows up in the side is up to the author since it's declared in the frontmatter of the markdown document. I turned on "Sample Pathway", but not the "Web Literacy Core Curriculum" as that seemed redundant.

It's all up on staging now if you want to check it out...

**Comment by sabrinang** [comment]
@gvn This looks great. The smooth scrolling and hiding the sub pages really help with navigating these copy heavy pages. Thanks for adding "sample pathway" it helps demo that smaller headings can be in the nav if users want to even if this is just placeholder content.

R+ from me!

**Comment by gvn** [comment]
@sabrinang How do you want to style the inline TOC?

**Comment by gvn** [comment]
@xmatthewx ^

**Comment by xmatthewx** [comment]
@gvn - I don't see a comp with anything specific for an inline TOC. As long we add indentation for nested lists, it'll be usable and good enough to ship. We could try the yellow box used on `<ol>` or wait for @sabrinang to return.

**Comment by gvn** [comment]
Ok, I added indentation for a clearer visual hierarchy.

**Pull request merged**
